// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="SimpleRxMCDMA_SimpleRxMCDMA,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku040-ffva1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.000000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1402,HLS_SYN_LUT=2424,HLS_VERSION=2022_2}" *)

module SimpleRxMCDMA (
        ap_clk,
        ap_rst_n,
        m_axi_mem_AWVALID,
        m_axi_mem_AWREADY,
        m_axi_mem_AWADDR,
        m_axi_mem_AWID,
        m_axi_mem_AWLEN,
        m_axi_mem_AWSIZE,
        m_axi_mem_AWBURST,
        m_axi_mem_AWLOCK,
        m_axi_mem_AWCACHE,
        m_axi_mem_AWPROT,
        m_axi_mem_AWQOS,
        m_axi_mem_AWREGION,
        m_axi_mem_AWUSER,
        m_axi_mem_WVALID,
        m_axi_mem_WREADY,
        m_axi_mem_WDATA,
        m_axi_mem_WSTRB,
        m_axi_mem_WLAST,
        m_axi_mem_WID,
        m_axi_mem_WUSER,
        m_axi_mem_ARVALID,
        m_axi_mem_ARREADY,
        m_axi_mem_ARADDR,
        m_axi_mem_ARID,
        m_axi_mem_ARLEN,
        m_axi_mem_ARSIZE,
        m_axi_mem_ARBURST,
        m_axi_mem_ARLOCK,
        m_axi_mem_ARCACHE,
        m_axi_mem_ARPROT,
        m_axi_mem_ARQOS,
        m_axi_mem_ARREGION,
        m_axi_mem_ARUSER,
        m_axi_mem_RVALID,
        m_axi_mem_RREADY,
        m_axi_mem_RDATA,
        m_axi_mem_RLAST,
        m_axi_mem_RID,
        m_axi_mem_RUSER,
        m_axi_mem_RRESP,
        m_axi_mem_BVALID,
        m_axi_mem_BREADY,
        m_axi_mem_BRESP,
        m_axi_mem_BID,
        m_axi_mem_BUSER,
        RX_stream_TDATA,
        RX_stream_TVALID,
        RX_stream_TREADY,
        RX_stream_TKEEP,
        RX_stream_TSTRB,
        RX_stream_TLAST,
        RX_stream_TDEST,
        s_axi_s_axi_ctrl_AWVALID,
        s_axi_s_axi_ctrl_AWREADY,
        s_axi_s_axi_ctrl_AWADDR,
        s_axi_s_axi_ctrl_WVALID,
        s_axi_s_axi_ctrl_WREADY,
        s_axi_s_axi_ctrl_WDATA,
        s_axi_s_axi_ctrl_WSTRB,
        s_axi_s_axi_ctrl_ARVALID,
        s_axi_s_axi_ctrl_ARREADY,
        s_axi_s_axi_ctrl_ARADDR,
        s_axi_s_axi_ctrl_RVALID,
        s_axi_s_axi_ctrl_RREADY,
        s_axi_s_axi_ctrl_RDATA,
        s_axi_s_axi_ctrl_RRESP,
        s_axi_s_axi_ctrl_BVALID,
        s_axi_s_axi_ctrl_BREADY,
        s_axi_s_axi_ctrl_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;
parameter    C_S_AXI_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_S_AXI_CTRL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_MEM_ID_WIDTH = 1;
parameter    C_M_AXI_MEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_MEM_DATA_WIDTH = 32;
parameter    C_M_AXI_MEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_TARGET_ADDR = 0;
parameter    C_M_AXI_MEM_USER_VALUE = 0;
parameter    C_M_AXI_MEM_PROT_VALUE = 0;
parameter    C_M_AXI_MEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_MEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_mem_AWVALID;
input   m_axi_mem_AWREADY;
output  [C_M_AXI_MEM_ADDR_WIDTH - 1:0] m_axi_mem_AWADDR;
output  [C_M_AXI_MEM_ID_WIDTH - 1:0] m_axi_mem_AWID;
output  [7:0] m_axi_mem_AWLEN;
output  [2:0] m_axi_mem_AWSIZE;
output  [1:0] m_axi_mem_AWBURST;
output  [1:0] m_axi_mem_AWLOCK;
output  [3:0] m_axi_mem_AWCACHE;
output  [2:0] m_axi_mem_AWPROT;
output  [3:0] m_axi_mem_AWQOS;
output  [3:0] m_axi_mem_AWREGION;
output  [C_M_AXI_MEM_AWUSER_WIDTH - 1:0] m_axi_mem_AWUSER;
output   m_axi_mem_WVALID;
input   m_axi_mem_WREADY;
output  [C_M_AXI_MEM_DATA_WIDTH - 1:0] m_axi_mem_WDATA;
output  [C_M_AXI_MEM_WSTRB_WIDTH - 1:0] m_axi_mem_WSTRB;
output   m_axi_mem_WLAST;
output  [C_M_AXI_MEM_ID_WIDTH - 1:0] m_axi_mem_WID;
output  [C_M_AXI_MEM_WUSER_WIDTH - 1:0] m_axi_mem_WUSER;
output   m_axi_mem_ARVALID;
input   m_axi_mem_ARREADY;
output  [C_M_AXI_MEM_ADDR_WIDTH - 1:0] m_axi_mem_ARADDR;
output  [C_M_AXI_MEM_ID_WIDTH - 1:0] m_axi_mem_ARID;
output  [7:0] m_axi_mem_ARLEN;
output  [2:0] m_axi_mem_ARSIZE;
output  [1:0] m_axi_mem_ARBURST;
output  [1:0] m_axi_mem_ARLOCK;
output  [3:0] m_axi_mem_ARCACHE;
output  [2:0] m_axi_mem_ARPROT;
output  [3:0] m_axi_mem_ARQOS;
output  [3:0] m_axi_mem_ARREGION;
output  [C_M_AXI_MEM_ARUSER_WIDTH - 1:0] m_axi_mem_ARUSER;
input   m_axi_mem_RVALID;
output   m_axi_mem_RREADY;
input  [C_M_AXI_MEM_DATA_WIDTH - 1:0] m_axi_mem_RDATA;
input   m_axi_mem_RLAST;
input  [C_M_AXI_MEM_ID_WIDTH - 1:0] m_axi_mem_RID;
input  [C_M_AXI_MEM_RUSER_WIDTH - 1:0] m_axi_mem_RUSER;
input  [1:0] m_axi_mem_RRESP;
input   m_axi_mem_BVALID;
output   m_axi_mem_BREADY;
input  [1:0] m_axi_mem_BRESP;
input  [C_M_AXI_MEM_ID_WIDTH - 1:0] m_axi_mem_BID;
input  [C_M_AXI_MEM_BUSER_WIDTH - 1:0] m_axi_mem_BUSER;
input  [31:0] RX_stream_TDATA;
input   RX_stream_TVALID;
output   RX_stream_TREADY;
input  [3:0] RX_stream_TKEEP;
input  [3:0] RX_stream_TSTRB;
input  [0:0] RX_stream_TLAST;
input  [1:0] RX_stream_TDEST;
input   s_axi_s_axi_ctrl_AWVALID;
output   s_axi_s_axi_ctrl_AWREADY;
input  [C_S_AXI_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_s_axi_ctrl_AWADDR;
input   s_axi_s_axi_ctrl_WVALID;
output   s_axi_s_axi_ctrl_WREADY;
input  [C_S_AXI_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_s_axi_ctrl_WDATA;
input  [C_S_AXI_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_s_axi_ctrl_WSTRB;
input   s_axi_s_axi_ctrl_ARVALID;
output   s_axi_s_axi_ctrl_ARREADY;
input  [C_S_AXI_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_s_axi_ctrl_ARADDR;
output   s_axi_s_axi_ctrl_RVALID;
input   s_axi_s_axi_ctrl_RREADY;
output  [C_S_AXI_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_s_axi_ctrl_RDATA;
output  [1:0] s_axi_s_axi_ctrl_RRESP;
output   s_axi_s_axi_ctrl_BVALID;
input   s_axi_s_axi_ctrl_BREADY;
output  [1:0] s_axi_s_axi_ctrl_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] channel_descr_addr_q0;
wire   [31:0] channel_descr_len_q0;
reg   [1:0] channel_descr_enable_address0;
reg    channel_descr_enable_ce0;
wire   [0:0] channel_descr_enable_q0;
reg   [1:0] channel_descr_done_address0;
reg    channel_descr_done_ce0;
reg    channel_descr_done_we0;
reg   [0:0] channel_descr_done_d0;
reg   [1:0] channel_descr_error_address0;
reg    channel_descr_error_ce0;
reg    channel_descr_error_we0;
reg   [0:0] channel_descr_error_d0;
reg   [1:0] channel_descr_transfered_data_address0;
reg    channel_descr_transfered_data_ce0;
reg    channel_descr_transfered_data_we0;
reg   [31:0] channel_descr_transfered_data_d0;
wire   [31:0] channel_descr_transfered_data_q0;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_ap_start;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_ap_done;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_ap_idle;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_ap_ready;
wire   [1:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_enable_address0;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_enable_ce0;
wire   [1:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_done_address0;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_done_ce0;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_done_we0;
wire   [0:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_done_d0;
wire   [1:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_error_address0;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_error_ce0;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_error_we0;
wire   [0:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_error_d0;
wire   [1:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_transfered_data_address0;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_transfered_data_ce0;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_transfered_data_we0;
wire   [31:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_transfered_data_d0;
wire   [7:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_n_remaining_channels_out;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_n_remaining_channels_out_ap_vld;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_ap_start;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_ap_done;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_ap_idle;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_ap_ready;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWVALID;
wire   [63:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWADDR;
wire   [0:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWID;
wire   [31:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWLEN;
wire   [2:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWSIZE;
wire   [1:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWBURST;
wire   [1:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWLOCK;
wire   [3:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWCACHE;
wire   [2:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWPROT;
wire   [3:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWQOS;
wire   [3:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWREGION;
wire   [0:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWUSER;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_WVALID;
wire   [31:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_WDATA;
wire   [3:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_WSTRB;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_WLAST;
wire   [0:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_WID;
wire   [0:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_WUSER;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_ARVALID;
wire   [63:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_ARADDR;
wire   [0:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_ARID;
wire   [31:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_ARLEN;
wire   [2:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_ARSIZE;
wire   [1:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_ARBURST;
wire   [1:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_ARLOCK;
wire   [3:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_ARCACHE;
wire   [2:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_ARPROT;
wire   [3:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_ARQOS;
wire   [3:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_ARREGION;
wire   [0:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_ARUSER;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_RREADY;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_BREADY;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_RX_stream_TREADY;
wire   [1:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_enable_address0;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_enable_ce0;
wire   [1:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_addr_address0;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_addr_ce0;
wire   [1:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_transfered_data_address0;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_transfered_data_ce0;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_transfered_data_we0;
wire   [31:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_transfered_data_d0;
wire   [1:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_len_address0;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_len_ce0;
wire   [1:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_done_address0;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_done_ce0;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_done_we0;
wire   [0:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_done_d0;
wire   [1:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_error_address0;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_error_ce0;
wire    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_error_we0;
wire   [0:0] grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_error_d0;
reg    mem_AWVALID;
wire    mem_AWREADY;
reg    mem_WVALID;
wire    mem_WREADY;
wire    mem_ARREADY;
wire    mem_RVALID;
wire   [31:0] mem_RDATA;
wire   [8:0] mem_RFIFONUM;
wire    mem_BVALID;
reg    mem_BREADY;
reg    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    regslice_both_RX_stream_V_data_V_U_apdone_blk;
wire   [31:0] RX_stream_TDATA_int_regslice;
wire    RX_stream_TVALID_int_regslice;
reg    RX_stream_TREADY_int_regslice;
wire    regslice_both_RX_stream_V_data_V_U_ack_in;
wire    regslice_both_RX_stream_V_keep_V_U_apdone_blk;
wire   [3:0] RX_stream_TKEEP_int_regslice;
wire    regslice_both_RX_stream_V_keep_V_U_vld_out;
wire    regslice_both_RX_stream_V_keep_V_U_ack_in;
wire    regslice_both_RX_stream_V_strb_V_U_apdone_blk;
wire   [3:0] RX_stream_TSTRB_int_regslice;
wire    regslice_both_RX_stream_V_strb_V_U_vld_out;
wire    regslice_both_RX_stream_V_strb_V_U_ack_in;
wire    regslice_both_RX_stream_V_last_V_U_apdone_blk;
wire   [0:0] RX_stream_TLAST_int_regslice;
wire    regslice_both_RX_stream_V_last_V_U_vld_out;
wire    regslice_both_RX_stream_V_last_V_U_ack_in;
wire    regslice_both_RX_stream_V_dest_V_U_apdone_blk;
wire   [1:0] RX_stream_TDEST_int_regslice;
wire    regslice_both_RX_stream_V_dest_V_U_vld_out;
wire    regslice_both_RX_stream_V_dest_V_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_ap_start_reg = 1'b0;
#0 grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_ap_start_reg = 1'b0;
end

SimpleRxMCDMA_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1 grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_ap_start),
    .ap_done(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_ap_done),
    .ap_idle(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_ap_idle),
    .ap_ready(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_ap_ready),
    .channel_descr_enable_address0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_enable_address0),
    .channel_descr_enable_ce0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_enable_ce0),
    .channel_descr_enable_q0(channel_descr_enable_q0),
    .channel_descr_done_address0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_done_address0),
    .channel_descr_done_ce0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_done_ce0),
    .channel_descr_done_we0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_done_we0),
    .channel_descr_done_d0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_done_d0),
    .channel_descr_error_address0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_error_address0),
    .channel_descr_error_ce0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_error_ce0),
    .channel_descr_error_we0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_error_we0),
    .channel_descr_error_d0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_error_d0),
    .channel_descr_transfered_data_address0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_transfered_data_address0),
    .channel_descr_transfered_data_ce0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_transfered_data_ce0),
    .channel_descr_transfered_data_we0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_transfered_data_we0),
    .channel_descr_transfered_data_d0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_transfered_data_d0),
    .n_remaining_channels_out(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_n_remaining_channels_out),
    .n_remaining_channels_out_ap_vld(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_n_remaining_channels_out_ap_vld)
);

SimpleRxMCDMA_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2 grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_ap_start),
    .ap_done(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_ap_done),
    .ap_idle(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_ap_idle),
    .ap_ready(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_ap_ready),
    .m_axi_mem_AWVALID(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWVALID),
    .m_axi_mem_AWREADY(mem_AWREADY),
    .m_axi_mem_AWADDR(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWADDR),
    .m_axi_mem_AWID(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWID),
    .m_axi_mem_AWLEN(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWLEN),
    .m_axi_mem_AWSIZE(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWSIZE),
    .m_axi_mem_AWBURST(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWBURST),
    .m_axi_mem_AWLOCK(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWLOCK),
    .m_axi_mem_AWCACHE(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWCACHE),
    .m_axi_mem_AWPROT(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWPROT),
    .m_axi_mem_AWQOS(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWQOS),
    .m_axi_mem_AWREGION(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWREGION),
    .m_axi_mem_AWUSER(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWUSER),
    .m_axi_mem_WVALID(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_WVALID),
    .m_axi_mem_WREADY(mem_WREADY),
    .m_axi_mem_WDATA(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_WDATA),
    .m_axi_mem_WSTRB(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_WSTRB),
    .m_axi_mem_WLAST(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_WLAST),
    .m_axi_mem_WID(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_WID),
    .m_axi_mem_WUSER(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_WUSER),
    .m_axi_mem_ARVALID(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_ARVALID),
    .m_axi_mem_ARREADY(1'b0),
    .m_axi_mem_ARADDR(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_ARADDR),
    .m_axi_mem_ARID(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_ARID),
    .m_axi_mem_ARLEN(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_ARLEN),
    .m_axi_mem_ARSIZE(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_ARSIZE),
    .m_axi_mem_ARBURST(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_ARBURST),
    .m_axi_mem_ARLOCK(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_ARLOCK),
    .m_axi_mem_ARCACHE(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_ARCACHE),
    .m_axi_mem_ARPROT(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_ARPROT),
    .m_axi_mem_ARQOS(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_ARQOS),
    .m_axi_mem_ARREGION(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_ARREGION),
    .m_axi_mem_ARUSER(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_ARUSER),
    .m_axi_mem_RVALID(1'b0),
    .m_axi_mem_RREADY(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_RREADY),
    .m_axi_mem_RDATA(32'd0),
    .m_axi_mem_RLAST(1'b0),
    .m_axi_mem_RID(1'd0),
    .m_axi_mem_RFIFONUM(9'd0),
    .m_axi_mem_RUSER(1'd0),
    .m_axi_mem_RRESP(2'd0),
    .m_axi_mem_BVALID(mem_BVALID),
    .m_axi_mem_BREADY(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_BREADY),
    .m_axi_mem_BRESP(2'd0),
    .m_axi_mem_BID(1'd0),
    .m_axi_mem_BUSER(1'd0),
    .n_remaining_channels_reload(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_n_remaining_channels_out),
    .RX_stream_TDATA(RX_stream_TDATA_int_regslice),
    .RX_stream_TVALID(RX_stream_TVALID_int_regslice),
    .RX_stream_TREADY(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_RX_stream_TREADY),
    .RX_stream_TKEEP(RX_stream_TKEEP_int_regslice),
    .RX_stream_TSTRB(RX_stream_TSTRB_int_regslice),
    .RX_stream_TLAST(RX_stream_TLAST_int_regslice),
    .RX_stream_TDEST(RX_stream_TDEST_int_regslice),
    .channel_descr_enable_address0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_enable_address0),
    .channel_descr_enable_ce0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_enable_ce0),
    .channel_descr_enable_q0(channel_descr_enable_q0),
    .channel_descr_addr_address0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_addr_address0),
    .channel_descr_addr_ce0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_addr_ce0),
    .channel_descr_addr_q0(channel_descr_addr_q0),
    .channel_descr_transfered_data_address0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_transfered_data_address0),
    .channel_descr_transfered_data_ce0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_transfered_data_ce0),
    .channel_descr_transfered_data_we0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_transfered_data_we0),
    .channel_descr_transfered_data_d0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_transfered_data_d0),
    .channel_descr_transfered_data_q0(channel_descr_transfered_data_q0),
    .channel_descr_len_address0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_len_address0),
    .channel_descr_len_ce0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_len_ce0),
    .channel_descr_len_q0(channel_descr_len_q0),
    .channel_descr_done_address0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_done_address0),
    .channel_descr_done_ce0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_done_ce0),
    .channel_descr_done_we0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_done_we0),
    .channel_descr_done_d0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_done_d0),
    .channel_descr_error_address0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_error_address0),
    .channel_descr_error_ce0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_error_ce0),
    .channel_descr_error_we0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_error_we0),
    .channel_descr_error_d0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_error_d0)
);

SimpleRxMCDMA_s_axi_ctrl_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_S_AXI_CTRL_DATA_WIDTH ))
s_axi_ctrl_s_axi_U(
    .AWVALID(s_axi_s_axi_ctrl_AWVALID),
    .AWREADY(s_axi_s_axi_ctrl_AWREADY),
    .AWADDR(s_axi_s_axi_ctrl_AWADDR),
    .WVALID(s_axi_s_axi_ctrl_WVALID),
    .WREADY(s_axi_s_axi_ctrl_WREADY),
    .WDATA(s_axi_s_axi_ctrl_WDATA),
    .WSTRB(s_axi_s_axi_ctrl_WSTRB),
    .ARVALID(s_axi_s_axi_ctrl_ARVALID),
    .ARREADY(s_axi_s_axi_ctrl_ARREADY),
    .ARADDR(s_axi_s_axi_ctrl_ARADDR),
    .RVALID(s_axi_s_axi_ctrl_RVALID),
    .RREADY(s_axi_s_axi_ctrl_RREADY),
    .RDATA(s_axi_s_axi_ctrl_RDATA),
    .RRESP(s_axi_s_axi_ctrl_RRESP),
    .BVALID(s_axi_s_axi_ctrl_BVALID),
    .BREADY(s_axi_s_axi_ctrl_BREADY),
    .BRESP(s_axi_s_axi_ctrl_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .channel_descr_addr_address0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_addr_address0),
    .channel_descr_addr_ce0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_addr_ce0),
    .channel_descr_addr_q0(channel_descr_addr_q0),
    .channel_descr_len_address0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_len_address0),
    .channel_descr_len_ce0(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_len_ce0),
    .channel_descr_len_q0(channel_descr_len_q0),
    .channel_descr_enable_address0(channel_descr_enable_address0),
    .channel_descr_enable_ce0(channel_descr_enable_ce0),
    .channel_descr_enable_q0(channel_descr_enable_q0),
    .channel_descr_done_address0(channel_descr_done_address0),
    .channel_descr_done_ce0(channel_descr_done_ce0),
    .channel_descr_done_we0(channel_descr_done_we0),
    .channel_descr_done_d0(channel_descr_done_d0),
    .channel_descr_error_address0(channel_descr_error_address0),
    .channel_descr_error_ce0(channel_descr_error_ce0),
    .channel_descr_error_we0(channel_descr_error_we0),
    .channel_descr_error_d0(channel_descr_error_d0),
    .channel_descr_transfered_data_address0(channel_descr_transfered_data_address0),
    .channel_descr_transfered_data_ce0(channel_descr_transfered_data_ce0),
    .channel_descr_transfered_data_we0(channel_descr_transfered_data_we0),
    .channel_descr_transfered_data_d0(channel_descr_transfered_data_d0),
    .channel_descr_transfered_data_q0(channel_descr_transfered_data_q0),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

SimpleRxMCDMA_mem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_MEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_MEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_MEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_MEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_MEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_MEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_MEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_MEM_BUSER_WIDTH ),
    .C_TARGET_ADDR( C_M_AXI_MEM_TARGET_ADDR ),
    .C_USER_VALUE( C_M_AXI_MEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_MEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_MEM_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
mem_m_axi_U(
    .AWVALID(m_axi_mem_AWVALID),
    .AWREADY(m_axi_mem_AWREADY),
    .AWADDR(m_axi_mem_AWADDR),
    .AWID(m_axi_mem_AWID),
    .AWLEN(m_axi_mem_AWLEN),
    .AWSIZE(m_axi_mem_AWSIZE),
    .AWBURST(m_axi_mem_AWBURST),
    .AWLOCK(m_axi_mem_AWLOCK),
    .AWCACHE(m_axi_mem_AWCACHE),
    .AWPROT(m_axi_mem_AWPROT),
    .AWQOS(m_axi_mem_AWQOS),
    .AWREGION(m_axi_mem_AWREGION),
    .AWUSER(m_axi_mem_AWUSER),
    .WVALID(m_axi_mem_WVALID),
    .WREADY(m_axi_mem_WREADY),
    .WDATA(m_axi_mem_WDATA),
    .WSTRB(m_axi_mem_WSTRB),
    .WLAST(m_axi_mem_WLAST),
    .WID(m_axi_mem_WID),
    .WUSER(m_axi_mem_WUSER),
    .ARVALID(m_axi_mem_ARVALID),
    .ARREADY(m_axi_mem_ARREADY),
    .ARADDR(m_axi_mem_ARADDR),
    .ARID(m_axi_mem_ARID),
    .ARLEN(m_axi_mem_ARLEN),
    .ARSIZE(m_axi_mem_ARSIZE),
    .ARBURST(m_axi_mem_ARBURST),
    .ARLOCK(m_axi_mem_ARLOCK),
    .ARCACHE(m_axi_mem_ARCACHE),
    .ARPROT(m_axi_mem_ARPROT),
    .ARQOS(m_axi_mem_ARQOS),
    .ARREGION(m_axi_mem_ARREGION),
    .ARUSER(m_axi_mem_ARUSER),
    .RVALID(m_axi_mem_RVALID),
    .RREADY(m_axi_mem_RREADY),
    .RDATA(m_axi_mem_RDATA),
    .RLAST(m_axi_mem_RLAST),
    .RID(m_axi_mem_RID),
    .RUSER(m_axi_mem_RUSER),
    .RRESP(m_axi_mem_RRESP),
    .BVALID(m_axi_mem_BVALID),
    .BREADY(m_axi_mem_BREADY),
    .BRESP(m_axi_mem_BRESP),
    .BID(m_axi_mem_BID),
    .BUSER(m_axi_mem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(mem_ARREADY),
    .I_ARADDR(64'd0),
    .I_ARLEN(32'd0),
    .I_RVALID(mem_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(mem_RDATA),
    .I_RFIFONUM(mem_RFIFONUM),
    .I_AWVALID(mem_AWVALID),
    .I_AWREADY(mem_AWREADY),
    .I_AWADDR(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWADDR),
    .I_AWLEN(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWLEN),
    .I_WVALID(mem_WVALID),
    .I_WREADY(mem_WREADY),
    .I_WDATA(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_WDATA),
    .I_WSTRB(grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_WSTRB),
    .I_BVALID(mem_BVALID),
    .I_BREADY(mem_BREADY)
);

SimpleRxMCDMA_regslice_both #(
    .DataWidth( 32 ))
regslice_both_RX_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(RX_stream_TDATA),
    .vld_in(RX_stream_TVALID),
    .ack_in(regslice_both_RX_stream_V_data_V_U_ack_in),
    .data_out(RX_stream_TDATA_int_regslice),
    .vld_out(RX_stream_TVALID_int_regslice),
    .ack_out(RX_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_RX_stream_V_data_V_U_apdone_blk)
);

SimpleRxMCDMA_regslice_both #(
    .DataWidth( 4 ))
regslice_both_RX_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(RX_stream_TKEEP),
    .vld_in(RX_stream_TVALID),
    .ack_in(regslice_both_RX_stream_V_keep_V_U_ack_in),
    .data_out(RX_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_RX_stream_V_keep_V_U_vld_out),
    .ack_out(RX_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_RX_stream_V_keep_V_U_apdone_blk)
);

SimpleRxMCDMA_regslice_both #(
    .DataWidth( 4 ))
regslice_both_RX_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(RX_stream_TSTRB),
    .vld_in(RX_stream_TVALID),
    .ack_in(regslice_both_RX_stream_V_strb_V_U_ack_in),
    .data_out(RX_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_RX_stream_V_strb_V_U_vld_out),
    .ack_out(RX_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_RX_stream_V_strb_V_U_apdone_blk)
);

SimpleRxMCDMA_regslice_both #(
    .DataWidth( 1 ))
regslice_both_RX_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(RX_stream_TLAST),
    .vld_in(RX_stream_TVALID),
    .ack_in(regslice_both_RX_stream_V_last_V_U_ack_in),
    .data_out(RX_stream_TLAST_int_regslice),
    .vld_out(regslice_both_RX_stream_V_last_V_U_vld_out),
    .ack_out(RX_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_RX_stream_V_last_V_U_apdone_blk)
);

SimpleRxMCDMA_regslice_both #(
    .DataWidth( 2 ))
regslice_both_RX_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(RX_stream_TDEST),
    .vld_in(RX_stream_TVALID),
    .ack_in(regslice_both_RX_stream_V_dest_V_U_ack_in),
    .data_out(RX_stream_TDEST_int_regslice),
    .vld_out(regslice_both_RX_stream_V_dest_V_U_vld_out),
    .ack_out(RX_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_RX_stream_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_ap_start_reg <= 1'b1;
        end else if ((grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_ap_ready == 1'b1)) begin
            grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_ap_start_reg <= 1'b1;
        end else if ((grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_ap_ready == 1'b1)) begin
            grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        RX_stream_TREADY_int_regslice = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_RX_stream_TREADY;
    end else begin
        RX_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        channel_descr_done_address0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_done_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        channel_descr_done_address0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_done_address0;
    end else begin
        channel_descr_done_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        channel_descr_done_ce0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_done_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        channel_descr_done_ce0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_done_ce0;
    end else begin
        channel_descr_done_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        channel_descr_done_d0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_done_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        channel_descr_done_d0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_done_d0;
    end else begin
        channel_descr_done_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        channel_descr_done_we0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_done_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        channel_descr_done_we0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_done_we0;
    end else begin
        channel_descr_done_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        channel_descr_enable_address0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_enable_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        channel_descr_enable_address0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_enable_address0;
    end else begin
        channel_descr_enable_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        channel_descr_enable_ce0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_enable_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        channel_descr_enable_ce0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_enable_ce0;
    end else begin
        channel_descr_enable_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        channel_descr_error_address0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_error_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        channel_descr_error_address0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_error_address0;
    end else begin
        channel_descr_error_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        channel_descr_error_ce0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_error_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        channel_descr_error_ce0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_error_ce0;
    end else begin
        channel_descr_error_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        channel_descr_error_d0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_error_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        channel_descr_error_d0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_error_d0;
    end else begin
        channel_descr_error_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        channel_descr_error_we0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_error_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        channel_descr_error_we0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_error_we0;
    end else begin
        channel_descr_error_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        channel_descr_transfered_data_address0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_transfered_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        channel_descr_transfered_data_address0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_transfered_data_address0;
    end else begin
        channel_descr_transfered_data_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        channel_descr_transfered_data_ce0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_transfered_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        channel_descr_transfered_data_ce0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_transfered_data_ce0;
    end else begin
        channel_descr_transfered_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        channel_descr_transfered_data_d0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_transfered_data_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        channel_descr_transfered_data_d0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_transfered_data_d0;
    end else begin
        channel_descr_transfered_data_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        channel_descr_transfered_data_we0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_channel_descr_transfered_data_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        channel_descr_transfered_data_we0 = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_channel_descr_transfered_data_we0;
    end else begin
        channel_descr_transfered_data_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        mem_AWVALID = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_AWVALID;
    end else begin
        mem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        mem_BREADY = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_BREADY;
    end else begin
        mem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        mem_WVALID = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_m_axi_mem_WVALID;
    end else begin
        mem_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign RX_stream_TREADY = regslice_both_RX_stream_V_data_V_U_ack_in;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_ap_start = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1_fu_96_ap_start_reg;

assign grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_ap_start = grp_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2_fu_109_ap_start_reg;


reg find_kernel_block = 0;
// synthesis translate_off
`include "SimpleRxMCDMA_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //SimpleRxMCDMA

