#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : tb.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Fri Apr 21 00:31:41 +0200 2023
# SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
#
# Tool Version Limit: 2022.10 
#
# usage: tb.sh [-help]
# usage: tb.sh [-lib_map_path]
# usage: tb.sh [-noclean_files]
# usage: tb.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'tb.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64 "

# Set vhdlan compile options
vhdlan_opts="-full64 "

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log "

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log "

# Design libraries
design_libs=(xilinx_vip xpm lmb_bram_if_cntlr_v4_0_21 xil_defaultlib lmb_v10_v3_0_12 blk_mem_gen_v8_4_5 axi_bram_ctrl_v4_1_7 xlconstant_v1_1_7 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 smartconnect_v1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_27 axi_vip_v1_1_13 axis_infrastructure_v1_1_0 axis_register_slice_v1_1_27 axis_switch_v1_1_27 axi_lite_ipif_v3_0_4 mdm_v3_2_23 microblaze_v11_0_10 axi_intc_v4_1_17 generic_baseblocks_v2_1_0 fifo_generator_v13_2_7 axi_data_fifo_v2_1_26 axi_crossbar_v2_1_28 xlconcat_v2_1_4 lib_pkg_v1_0_2 lib_srl_fifo_v1_0_2 axi_uartlite_v2_0_31 axi_timer_v2_0_29)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "tb.sh - Script generated by export_simulation (Vivado v2022.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "E:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "E:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "E:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "E:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_bram_if_cntlr_v4_0_21 $vhdlan_opts \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/a177/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/tb/ip/tb_dlmb_bram_if_cntlr_0/sim/tb_dlmb_bram_if_cntlr_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_v10_v3_0_12 $vhdlan_opts \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cd1d/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/tb/ip/tb_dlmb_v10_0/sim/tb_dlmb_v10_0.vhd" \
    "$ref_dir/../../../bd/tb/ip/tb_ilmb_bram_if_cntlr_0/sim/tb_ilmb_bram_if_cntlr_0.vhd" \
    "$ref_dir/../../../bd/tb/ip/tb_ilmb_v10_0/sim/tb_ilmb_v10_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/25a8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/tb/ip/tb_lmb_bram_0/sim/tb_lmb_bram_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_bram_ctrl_v4_1_7 $vhdlan_opts \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f80b/hdl/axi_bram_ctrl_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/tb/ip/tb_axi_bram_ctrl_0_0/sim/tb_axi_bram_ctrl_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/sim/bd_5cf0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/badb/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_0/sim/bd_5cf0_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_1/sim/bd_5cf0_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_2/sim/bd_5cf0_arsw_0.sv" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_3/sim/bd_5cf0_rsw_0.sv" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_4/sim/bd_5cf0_awsw_0.sv" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_5/sim/bd_5cf0_wsw_0.sv" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_6/sim/bd_5cf0_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/be1f/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_7/sim/bd_5cf0_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/4fd2/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_8/sim/bd_5cf0_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/637d/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_9/sim/bd_5cf0_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f38e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_10/sim/bd_5cf0_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_11/sim/bd_5cf0_sarn_0.sv" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_12/sim/bd_5cf0_srn_0.sv" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_13/sim/bd_5cf0_s01mmu_0.sv" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_14/sim/bd_5cf0_s01tr_0.sv" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_15/sim/bd_5cf0_s01sic_0.sv" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_16/sim/bd_5cf0_s01a2s_0.sv" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_17/sim/bd_5cf0_sawn_0.sv" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_18/sim/bd_5cf0_swn_0.sv" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_19/sim/bd_5cf0_sbn_0.sv" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_20/sim/bd_5cf0_s02mmu_0.sv" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_21/sim/bd_5cf0_s02tr_0.sv" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_22/sim/bd_5cf0_s02sic_0.sv" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_23/sim/bd_5cf0_s02a2s_0.sv" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_24/sim/bd_5cf0_sarn_1.sv" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_25/sim/bd_5cf0_srn_1.sv" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_26/sim/bd_5cf0_sawn_1.sv" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_27/sim/bd_5cf0_swn_1.sv" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_28/sim/bd_5cf0_sbn_1.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/9cc5/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_29/sim/bd_5cf0_m00s2a_0.sv" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_30/sim/bd_5cf0_m00arn_0.sv" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_31/sim/bd_5cf0_m00rn_0.sv" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_32/sim/bd_5cf0_m00awn_0.sv" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_33/sim/bd_5cf0_m00wn_0.sv" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_34/sim/bd_5cf0_m00bn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/6bba/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_35/sim/bd_5cf0_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b4/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ffc2/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/tb/ip/tb_axi_smc_0/sim/tb_axi_smc_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_register_slice_v1_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/6ba3/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_switch_v1_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/1b0f/hdl/axis_switch_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/tb/ip/tb_xbar_3/sim/tb_xbar_3.v" \
    "$ref_dir/../../../bd/tb/ip/tb_xbar_4/sim/tb_xbar_4.v" \
    "$ref_dir/../../../bd/tb/ip/tb_blk_mem_gen_0_0/sim/tb_blk_mem_gen_0_0.v" \
    "$ref_dir/../../../bd/tb/ip/tb_clk_wiz_0/tb_clk_wiz_0_clk_wiz.v" \
    "$ref_dir/../../../bd/tb/ip/tb_clk_wiz_0/tb_clk_wiz_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mdm_v3_2_23 $vhdlan_opts \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/b8f4/hdl/mdm_v3_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/tb/ip/tb_mdm_1_0/sim/tb_mdm_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work microblaze_v11_0_10 $vhdlan_opts \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/1f7b/hdl/microblaze_v11_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/tb/ip/tb_microblaze_0_0/sim/tb_microblaze_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_intc_v4_1_17 $vhdlan_opts \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/802b/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/tb/ip/tb_microblaze_0_axi_intc_0/sim/tb_microblaze_0_axi_intc_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/83df/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_7 $vhdlan_opts \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/83df/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/83df/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/3111/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_28 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/c40e/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/tb/ip/tb_xbar_5/sim/tb_xbar_5.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/tb/ip/tb_microblaze_0_xlconcat_0/sim/tb_microblaze_0_xlconcat_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/tb/ip/tb_rst_clk_wiz_100M_0/sim/tb_rst_clk_wiz_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uartlite_v2_0_31 $vhdlan_opts \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/67a1/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/tb/ip/tb_axi_uartlite_0_0/sim/tb_axi_uartlite_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_timer_v2_0_29 $vhdlan_opts \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/22b2/hdl/axi_timer_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/tb/ip/tb_axi_timer_0_0/sim/tb_axi_timer_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/7698" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/drivers/SimpleRxMCDMA_v0_3/src" +incdir+"$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/drivers/SimpleTxMCDMA_v0_3/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog/SimpleRxMCDMA_flow_control_loop_pipe_sequential_init.v" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog/SimpleRxMCDMA_hls_deadlock_idx0_monitor.v" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog/SimpleRxMCDMA_mem_m_axi.v" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog/SimpleRxMCDMA_regslice_both.v" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog/SimpleRxMCDMA_s_axi_ctrl_s_axi.v" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog/SimpleRxMCDMA_SimpleRxMCDMA_Pipeline_VITIS_LOOP_13_1.v" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog/SimpleRxMCDMA_SimpleRxMCDMA_Pipeline_VITIS_LOOP_25_2.v" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/873f/hdl/verilog/SimpleRxMCDMA.v" \
    "$ref_dir/../../../bd/tb/ip/tb_SimpleRxMCDMA_0_0/sim/tb_SimpleRxMCDMA_0_0.v" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog/SimpleTxMCDMA_flow_control_loop_pipe_sequential_init.v" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog/SimpleTxMCDMA_hls_deadlock_idx0_monitor.v" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog/SimpleTxMCDMA_mem_m_axi.v" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog/SimpleTxMCDMA_regslice_both.v" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog/SimpleTxMCDMA_s_axi_ctrl_s_axi.v" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog/SimpleTxMCDMA_SimpleTxMCDMA_Pipeline_VITIS_LOOP_17_2.v" \
    "$ref_dir/../../../../MCDMA_TB.gen/sources_1/bd/tb/ipshared/cf8d/hdl/verilog/SimpleTxMCDMA.v" \
    "$ref_dir/../../../bd/tb/ip/tb_SimpleTxMCDMA_0_0/sim/tb_SimpleTxMCDMA_0_0.v" \
    "$ref_dir/../../../bd/tb/ip/tb_s_arb_req_suppress_concat_0/sim/tb_s_arb_req_suppress_concat_0.v" \
    "$ref_dir/../../../bd/tb/sim/tb.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.tb xil_defaultlib.glbl -o tb_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./tb_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./tb.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key tb_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc tb_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./tb.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: tb.sh [-help]\n\
Usage: tb.sh [-lib_map_path]\n\
Usage: tb.sh [-reset_run]\n\
Usage: tb.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
