# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "E:/Files/Test_benches/MCDMA_TB/MCDMA_TB.runs/synth_1/tb_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_msg_config -id {HDL-1065} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcku025-ffva1156-1-c

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Files/Test_benches/MCDMA_TB/MCDMA_TB.cache/wt [current_project]
set_property parent.project_path E:/Files/Test_benches/MCDMA_TB/MCDMA_TB.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths e:/Files/Test_benches/MCDMA_TB/IP_repo [current_project]
update_ip_catalog
set_property ip_output_repo e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib E:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/hdl/tb_wrapper.v
add_files E:/Files/Test_benches/MCDMA_TB/MCDMA_TB.srcs/sources_1/bd/tb/tb.bd
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_dlmb_bram_if_cntlr_0/tb_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_dlmb_v10_0/tb_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_ilmb_bram_if_cntlr_0/tb_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_ilmb_v10_0/tb_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_lmb_bram_0/tb_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_bram_ctrl_0_0/tb_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_1/bd_5cf0_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_1/bd_5cf0_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_2/bd_5cf0_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_3/bd_5cf0_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_4/bd_5cf0_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_5/bd_5cf0_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_6/bd_5cf0_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_10/bd_5cf0_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_11/bd_5cf0_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_12/bd_5cf0_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_16/bd_5cf0_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_17/bd_5cf0_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_18/bd_5cf0_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_19/bd_5cf0_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_23/bd_5cf0_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_24/bd_5cf0_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_25/bd_5cf0_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_26/bd_5cf0_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_27/bd_5cf0_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_28/bd_5cf0_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_29/bd_5cf0_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_30/bd_5cf0_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_31/bd_5cf0_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_32/bd_5cf0_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_33/bd_5cf0_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/bd_0/ip/ip_34/bd_5cf0_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_xbar_3/tb_xbar_3_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_xbar_4/tb_xbar_4_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_blk_mem_gen_0_0/tb_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_clk_wiz_0/tb_clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_clk_wiz_0/tb_clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_clk_wiz_0/tb_clk_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_mdm_1_0/tb_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_mdm_1_0/tb_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_microblaze_0_0/tb_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_microblaze_0_0/tb_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_microblaze_0_0/tb_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_microblaze_0_axi_intc_0/tb_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_microblaze_0_axi_intc_0/tb_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_microblaze_0_axi_intc_0/tb_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_xbar_5/tb_xbar_5_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_rst_clk_wiz_100M_0/tb_rst_clk_wiz_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_rst_clk_wiz_100M_0/tb_rst_clk_wiz_100M_0.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_rst_clk_wiz_100M_0/tb_rst_clk_wiz_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_uartlite_0_0/tb_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_uartlite_0_0/tb_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_uartlite_0_0/tb_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_timer_0_0/tb_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_axi_timer_0_0/tb_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleRxMCDMA_0_0/constraints/SimpleRxMCDMA_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_SimpleTxMCDMA_0_0/constraints/SimpleTxMCDMA_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/tb_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Files/Test_benches/MCDMA_TB/MCDMA_TB.gen/sources_1/bd/tb/ip/tb_microblaze_0_0/data/mb_bootloop_le.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Files/Test_benches/MCDMA_TB/MCDMA_TB.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files E:/Files/Test_benches/MCDMA_TB/MCDMA_TB.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental E:/Files/Test_benches/MCDMA_TB/MCDMA_TB.srcs/utils_1/imports/synth_1/tb_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top tb_wrapper -part xcku025-ffva1156-1-c
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef tb_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file tb_wrapper_utilization_synth.rpt -pb tb_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
